import fs from 'node:fs';
let s=fs.readFileSync('dist/cube-scene.js','utf8');s=s.replace('tile.material=this.tileMaterials[s.c];','tile.userData.sticker={p:[...s.p],n:[...s.n]};tile.material=this.tileMaterials[s.c];');fs.writeFileSync('dist/cube-scene.js',s);
s=fs.readFileSync('dist/cube.js','utf8');s=s.replace('side*p[axis]>m-width','prefix&&!wide?side*p[axis]===m-width+1:side*p[axis]>m-width');fs.writeFileSync('dist/cube.js',s);
s=fs.readFileSync('dist/game-v2.js','utf8');
s=s.replace('function cancelTurns(){generation++;','function cancelTurns(){cubeScene.cancelLayerDrag?.();generation++;');
s=s.replace('function animateTurn(token,version,speed){','function animateTurn(token,version,speed,fromAngle=0){');
s=s.replace('angle:plan.dir*plan.turns*Math.PI/2*eased','angle:fromAngle+(plan.dir*plan.turns*Math.PI/2-fromAngle)*eased');
s=s.replace('function queueTurn(token,onComplete=()=>{},speed){','function queueTurn(token,onComplete=()=>{},speed,fromAngle=0){');
s=s.replace('turnQueue.push({token,onComplete,speed})','turnQueue.push({token,onComplete,speed,fromAngle})');
s=s.replace('animateTurn(job.token,version,job.speed)','animateTurn(job.token,version,job.speed,job.fromAngle)');
s=s.replace('function manualTurn(token){','function manualTurn(token,fromAngle=0){');s=s.replace('queueTurn(token,()=>history.push(token))','queueTurn(token,()=>history.push(token),undefined,fromAngle)');
s=s.replace("['R','U','F','L','D','B'].forEach(f=>", "cubeScene.enableLayerDrag({canTurn:()=>!processing&&!scrambling&&!playing,onPreview:(token,angle)=>{animation={...movePlan(token,size),angle};canvas.dataset.dragMove=token;draw()},onTurn:(token,angle)=>{canvas.dataset.dragMove='';manualTurn(token,angle)},onCancel:()=>{animation=null;canvas.dataset.dragMove='';draw()}});\n['R','U','F','L','D','B'].forEach(f=>");
s=s.replace('b.textContent=token;', "b.textContent=({R:'右面',U:'顶面',F:'前面',L:'左面',D:'底面',B:'后面'})[f]+(token.endsWith(\"'\")?' ↶':' ↷');b.title=token;");
fs.writeFileSync('dist/game-v2.js',s);
s=fs.readFileSync('dist/index.html','utf8');s=s.replace('互动魔方，拖动改变视角，使用下方按钮或键盘转动','互动魔方，按住色块拖动转层，拖动空白调整视角');s=s.replace('拖动旋转视角 · 滚轮缩放 · R U F L D B 转面 · Shift 反向','按住色块拖动转层 · 拖动空白调整视角 · 滚轮缩放');s=s.replace('先点“打乱”，再试着还原。<br>不用着急，每一转都有新发现。','按住任意色块，朝想转的方向拖。<br>每一层都能直接转，试试看吧！');s=s.replace('拖动魔方查看不同面。点击面转按钮，或按 R / U / F / L / D / B 转动；按住 Shift 是逆时针。空格开始或停止计时。','按住魔方上的色块，沿横向或纵向拖动即可转动对应的一层，松手后自动转到位。拖动魔方旁的空白调整视角，滚轮缩放。下方的中文按钮也能转动各面。空格开始或停止计时。');fs.writeFileSync('dist/index.html',s);
